apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-api-proxy.name" . }}
    helm.sh/chart: {{ include "k8s-api-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Chart.Name }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "k8s-api-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
